Repository HacktoberBlog/hackerblog-frontend, pull requests merged in 2025-10, with the labels that each got.

#8 feat: I created the docs folder, translated the contributing and readme files into Brazilian Portuguese.
  docs/CONTRIBUTING-PT-BR.md
  docs/README-PT-BR.md
Labels: documentation

#13 Added eye button for password view - Both login and signup
  src/pages/AuthPages.css
  src/pages/LoginPage.jsx
  src/pages/RegisterPage.jsx
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#26 feat: add footer
  .gitignore
  src/components/Footer.css
  src/components/Footer.jsx
  src/pages/LandingPage.jsx
Labels: enhancement

#56 feat: mention tailwind css as default styling
  CONTRIBUTING.md
  README.md
  docs/br/CONTRIBUTING-PT-BR.md
  docs/br/README-PT-BR.md
  docs/en/CONTRIBUTING.md
  docs/en/README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#27 feat: made the navbar responsive
  src/components/TopBar.css
  src/components/TopBar.jsx
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted
